### ISSUE TITLE
CNN probability Folder

### ISSUE THREAD

**Issue by RagMeh11** [tsogkas/brainseg#1]
HI,

I downloaded cnn_prob_nii.zip and RF_prob.zip files. I was able to unzip RF_prob.zip file, but when I am trying to unzip cnn_prob_nii.zip file, it is showing me error that some part of zip file is missing. 

Can you please look into this, can upload cnn_prob_nii.zip file with all the files??

Thanks.

**Comment by eferrante** [comment]
Hi! Thanks for your comment. It seems that we are having a problem with the server, which is interrupting the connection when downloading a file that is bigger than 1GB. As a quick workaround, if you are using Linux, you can download the file using:

`$ wget http://cvn.ecp.fr/data/brainsegm/cnn_prob_nii.zip`

Wget will resume the interrupted connection and download the complete file.

We'll soon upload the cnn_prob_nii in 4 different folds, to avoid the server restrictions. 

Cheers,
Enzo

**Comment by RagMeh11** [comment]
Thanks. Was able to download through wget.

**Comment by RagMeh11** [comment]
Hi,

original images from IBSR nitrc repository is of size 256 \* 256 \* 128, while the probability maps you have uploaded is of size 145 \* 158 \* 123.

I know voxel size for both are same, 0.9375 \* 0.9375 \* 1.5, so it looks like here you have just reduced the image size by eliminating background pixel, I am not sure how much from each side you have cropped for this.

Can you please either upload the ground truth of the same size, or let me know the exact size of reduction from each 6 sides, so that I can easily compare it with IBSR groundtruth provided on nitrc repository??

Thanks.

**Comment by tsogkas** [comment]
Indeed, we had used cropped versions of the volumes to reduce computational cost. We did not provide a link to the cropped version of the dataset to avoid copyright issues (since access to IBSR requires registration on the NITRC website).

We will figure out how to best handle this issue and get back to you soon.

**Comment by RagMeh11** [comment]
I have registered at NITRC and downloaded the data, so I think the best way to handle this situation is if you can just let me know from each 6 (AP,SI,LR) sides how many voxels you have cropped, as every image is of the same size, then I can compare it with NITRC groundtruth.

**Comment by RagMeh11** [comment]
hi,

any solution for this problem??

**Comment by eferrante** [comment]
Hi, I already emailed the original cropped files to your private email.

If somebody else is having the same problem, please do not hesitate to email me and I'll provide the files.

**Comment by RagMeh11** [comment]
Thanks a lot !!

**Comment by mosbahi1** [comment]
Hi,I have some problems in running cnn.m
